"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import "../styles/global.css";
import ProgressBar from "@badrap/bar-of-progress";
import Router from "next/router";

//Build the progress Bar that takes an argument of an object
const progress = new ProgressBar({
  size: 12,
  color: "red",
  className: "z-50",
  delay: 200,
});

//Make a connection to the Router
Router.events.on("routeChangeStart", progress.start);
Router.events.on("routeChangeComplete", progress.finish);
Router.events.on("routeChangeError", progress.finish);

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
